### ISSUE TITLE
Documentar funções

### ISSUE THREAD

**Issue by gustavonikov** [chaordic/frontend-developer-challenge#3]
Com documente suas funções, vocês querem dizer usar Docblock? ou usar comentários no código normal explicando a função?

**Comment by Markkop** [comment]
E aí, @gustavonikov!
A documentação do projeto fica a seu critério. 
De repente vale dar uma pesquisada sobre quais ferramentas e melhores práticas existem por aí em relação a documentação de JavaScript.
Qualquer outra dúvida manda aí!
Abraços!

**Comment by gustavonikov** [comment]
Sim sim, acabei por optar pell Docblock padrão Javascript, mas obrigado pelo reply :)
